export function generateReceiptPDF(appointment) {
    const urgencyLabels = { 1: 'Routine', 2: 'Low', 3: 'Moderate', 4: 'High', 5: 'Critical' };

    const html = `
    <div style="font-family: 'Segoe UI', sans-serif; max-width: 500px; margin: 0 auto; padding: 40px 30px; color: #1e293b;">
      <div style="text-align: center; margin-bottom: 30px;">
        <div style="display: inline-block; background: #2563eb; color: white; padding: 8px 20px; border-radius: 12px; font-size: 20px; font-weight: 900; letter-spacing: 1px;">
          PULSE AI
        </div>
        <p style="color: #94a3b8; font-size: 12px; margin-top: 8px;">Appointment Confirmation Receipt</p>
      </div>

      <hr style="border: none; border-top: 2px solid #e2e8f0; margin: 20px 0;" />

      <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
        <tr>
          <td style="padding: 10px 0; color: #64748b; font-weight: 600;">Patient Name</td>
          <td style="padding: 10px 0; text-align: right; font-weight: 700;">${appointment.patientName}</td>
        </tr>
        <tr>
          <td style="padding: 10px 0; color: #64748b; font-weight: 600;">Department</td>
          <td style="padding: 10px 0; text-align: right; font-weight: 700;">${appointment.department}</td>
        </tr>
        <tr>
          <td style="padding: 10px 0; color: #64748b; font-weight: 600;">Date</td>
          <td style="padding: 10px 0; text-align: right; font-weight: 700;">${appointment.date}</td>
        </tr>
        <tr>
          <td style="padding: 10px 0; color: #64748b; font-weight: 600;">Time</td>
          <td style="padding: 10px 0; text-align: right; font-weight: 700;">${appointment.time}</td>
        </tr>
        <tr>
          <td style="padding: 10px 0; color: #64748b; font-weight: 600;">Urgency Level</td>
          <td style="padding: 10px 0; text-align: right;">
            <span style="background: ${appointment.urgency >= 4 ? '#fee2e2' : appointment.urgency === 3 ? '#fef3c7' : '#d1fae5'}; color: ${appointment.urgency >= 4 ? '#b91c1c' : appointment.urgency === 3 ? '#92400e' : '#047857'}; padding: 3px 10px; border-radius: 20px; font-size: 12px; font-weight: 700;">
              ${urgencyLabels[appointment.urgency] || 'Unknown'}
            </span>
          </td>
        </tr>
        <tr>
          <td style="padding: 10px 0; color: #64748b; font-weight: 600;">Status</td>
          <td style="padding: 10px 0; text-align: right;">
            <span style="background: #d1fae5; color: #047857; padding: 3px 10px; border-radius: 20px; font-size: 12px; font-weight: 700;">
              ✓ Confirmed
            </span>
          </td>
        </tr>
        <tr>
          <td style="padding: 10px 0; color: #64748b; font-weight: 600;">Booking ID</td>
          <td style="padding: 10px 0; text-align: right; font-family: monospace; font-size: 12px; color: #94a3b8;">${appointment.id}</td>
        </tr>
      </table>

      ${appointment.triageSummary ? `
        <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 20px 0;" />
        <div style="background: #f8fafc; padding: 16px; border-radius: 12px; margin-bottom: 12px;">
          <p style="font-size: 11px; color: #94a3b8; font-weight: 700; text-transform: uppercase; letter-spacing: 1px; margin: 0 0 6px;">AI Assessment</p>
          <p style="font-size: 13px; color: #475569; margin: 0;">${appointment.triageSummary}</p>
        </div>
        <div style="background: #f8fafc; padding: 16px; border-radius: 12px;">
          <p style="font-size: 11px; color: #94a3b8; font-weight: 700; text-transform: uppercase; letter-spacing: 1px; margin: 0 0 6px;">Recommendation</p>
          <p style="font-size: 13px; color: #475569; margin: 0;">${appointment.recommendation}</p>
        </div>
      ` : ''}

      <hr style="border: none; border-top: 2px solid #e2e8f0; margin: 24px 0;" />

      <p style="text-align: center; font-size: 11px; color: #94a3b8;">
        Generated by PULSE AI • ${new Date().toLocaleString()}<br/>
        This is not a substitute for professional medical advice.
      </p>
    </div>
  `;

    const printWindow = window.open('', '_blank', 'width=600,height=800');
    printWindow.document.write(`
    <html>
      <head><title>PULSE AI Receipt — ${appointment.patientName}</title></head>
      <body style="margin: 0;">${html}</body>
    </html>
  `);
    printWindow.document.close();
    printWindow.focus();
    printWindow.print();
}
